# themes from https://github.com/alacritty/alacritty-theme

import = ["~/.config/alacritty/themes/themes/Cobalt2.toml"]

[font]
size = 25

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
# decorations = "none"

[window.padding]
x = 7
y = 0

